language: erlang
otp_release:
  - 17.1
  - 17.0
env:
  - BUILD_TYPE=rebar REBAR_ENV=test ELIXIR_VERSION=stable
  - BUILD_TYPE=mix MIX_ENV=test ELIXIR_VERSION=stable
  - BUILD_TYPE=rebar REBAR_ENV=test ELIXIR_VERSION=v0.14.3
  - BUILD_TYPE=mix MIX_ENV=test ELIXIR_VERSION=v0.14.3

install: "./.travis_install"
script: "./.travis_build"
